name: coffsy_movie_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 13.0.2+4

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Modules
  # UI
  shimmer: ^2.0.0
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.6
  youtube_player_flutter: ^8.0.0
  flutter_svg: ^0.22.0
  liquid_pull_to_refresh: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  lottie: ^1.0.1
  fluttertoast: ^8.0.7
  animated_card: ^2.0.0

  # Structure
  flutter_triple: 1.2.4+3
  flutter_modular: ^4.1.2

  # Others
  package_info: ^2.0.2
  feedback: ^2.0.0
  dartz: ^0.10.0

  # Firebase
  firebase_performance: ^0.7.0
  firebase_remote_config: 0.10.0+3
  firebase_crashlytics: ^2.0.7
  firebase_analytics: ^8.1.2
  firebase_storage: ^10.0.2

  # Core
  shared_preferences: ^2.0.6
  equatable: ^2.0.2
  dio: ^4.0.0
  effective_dart: ^1.3.2
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  mocktail: ^0.1.1
  modular_test: ^1.0.1+1
  integration_test:
    sdk: flutter
  triple_test: ^0.0.8
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/movie_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          style: italic
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
